---
- name: Launch Docker Container
  hosts: prod
  become: yes
  vars:
    docker_image: "garvbakliwal/docker-jenkins-project"
    docker_tag: "latest"
    container_name: "con1"
    host_port: "80"
    container_port: "80"
  tasks:
    - name: Remove old container if it exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes

    - name: Remove all Docker images if they exist
      shell: |
        images=$(docker images -qa)
        if [ -n "$images" ]; then
          docker rmi -f $images
        fi
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        source: pull

    - name: Run the new Docker Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        published_ports: "{{ host_port }}:{{ container_port }}"

    - name: Show running containers
      shell: docker ps
      register: docker_ps_output

    - name: Display container list
      debug:
        var: docker_ps_output.stdout_lines
